---
version: "2.0"

services:
  web:
    image: freedom-central
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 512Mi
        storage:
          size: 512Mi
  placement:
    westcoast:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1r89srvqvhd740ydpzvsfu9ry9jj8z3ahn56mvy"
      pricing:
        web: 
          denom: uakt
          amount: 1000

deployment:
  web:
    westcoast:
      profile: web
      count: 1

